//
// This file lists all the battle node UIDs in an easy to remember form...
//
//

#define	set(id)	UID_BNE_##id

//NODE(0a),NODE(0b),NODE(0c),NODE(0d),NODE(0e),NODE(0f),
//NODE(1a),NODE(1b),NODE(1c),NODE(1d),NODE(1e),NODE(1f),
//NODE(2a),NODE(2b),NODE(2c),NODE(2d),NODE(2e),NODE(2f),
//NODE(3a),NODE(3b),NODE(3c),NODE(3d),NODE(3e),NODE(3f),
//NODE(4a),NODE(4b),NODE(4c),NODE(4d),NODE(4e),NODE(4f),
//NODE(5a),NODE(5b),NODE(5c),NODE(5d),NODE(5e),NODE(5f),
//NODE(6a),NODE(6b),NODE(6c),NODE(6d),NODE(6e),NODE(6f),
//NODE(7a),NODE(7b),NODE(7c),NODE(7d),NODE(7e),NODE(7f),
#undef set										 
#define	set(id)	UID_BNC_##id

NODE(0a),NODE(0b),NODE(0c),NODE(0d),NODE(0e),NODE(0f),
NODE(1a),NODE(1b),NODE(1c),NODE(1d),NODE(1e),NODE(1f),
NODE(2a),NODE(2b),NODE(2c),NODE(2d),//NODE(2e),NODE(2f),
NODE(3a),NODE(3b),NODE(3c),//NODE(3d),NODE(3e),NODE(3f),
NODE(4a),//NODE(4b),NODE(4c),NODE(4d),NODE(4e),NODE(4f),
//NODE(5a),NODE(5b),NODE(5c),NODE(5d),NODE(5e),NODE(5f),
//NODE(6a),NODE(6b),NODE(6c),NODE(6d),NODE(6e),NODE(6f),
//NODE(7a),NODE(7b),NODE(7c),NODE(7d),NODE(7e),NODE(7f),

#undef set										 
#define	set(id)	UID_BNW_##id

NODE(0a),NODE(0b),NODE(0c),NODE(0d),NODE(0e),NODE(0f),
NODE(1a),NODE(1b),NODE(1c),NODE(1d),NODE(1e),NODE(1f),
NODE(2a),NODE(2b),NODE(2c),NODE(2d),//NODE(2e),//NODE(2f),
NODE(3a),NODE(3b),//NODE(3c),//NODE(3d),NODE(3e),NODE(3f),
NODE(4a),NODE(4b),//NODE(4c),NODE(4d),NODE(4e),NODE(4f),
NODE(5a),//NODE(5b),NODE(5c),NODE(5d),NODE(5e),NODE(5f),
//NODE(6a),NODE(6b),NODE(6c),NODE(6d),NODE(6e),NODE(6f),
//NODE(7a),NODE(7b),NODE(7c),NODE(7d),NODE(7e),NODE(7f),

#undef set										 
