//Initialising response file
//List of all initialising files and what they contain
//Types of content are: 
//Type	- associates enums with types,
//enum  - defines entries in enums
//Setval- associates main program globals with types or enums
//Posn	- 3dstudio positional info
{
	Type	bfields\initial.typ,
	enum	h\sounds.g,
	enum	h\shapenum.g,
	enum	h\worldinc.h,
	enum	h\movement.h,
	enum	h\ranges.h,
	enum	h\persons2.h,
	enum	h\uniqueid.h,
	enum	h\myangles.h,
	enum	h\flyinit.h ,
	enum	h\misssub.h,
	enum	h\transite.h,
	enum	h\viewsel.h,
	enum	h\batnode.h,
//	Posn	bfields\franc.asc,
	Setval	bfields\globrefs.txt
}
