//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RListBox.rc
//
#define IDS_RLISTBOX                    1
#define IDB_RLISTBOX                    1
#define IDS_RLISTBOX_PPG                2
#define IDS_RLISTBOX_PPG_CAPTION        200
#define IDD_PROPPAGE_RLISTBOX           200
#define IDC_IS_STRIPEY                  201
#define IDB_BITMAP1                     202
#define IDC_LINES                       202
#define IDC_LOCK_LEFT_COLUMN            203
#define IDC_LOCK_TOP_ROW                204
#define IDC_DRAG_AND_DROP               205
#define IDC_BLACKBOARD                  206
#define IDC_FONT_NUMBER                 207
#define IDC_FONT_NUMBER2                208
#define IDC_LINES2                      209
#define IDC_SELECT_WHOLE_ROWS           210
#define IDC_SELECT_WHOLE_ROWS2          211
#define IDC_HORZ_SEPERATION             212
#define IDC_VERT_SEPERATION             213
#define IDC_CENTRED                     215

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        203
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         207
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
