rem transfers important files for artists....

copy ..\game\mig.exe s:\transfer\robert\thegame\
copy h\3dinstr.h s:\transfer\robert\thegame\
copy h\3ddefs.h s:\transfer\robert\thegame\
copy h\shpinstr.h s:\transfer\robert\thegame\
copy h\animdata.h s:\transfer\robert\thegame\
copy landmap.fil s:\transfer\robert\thegame\
copy sounds.fil s:\transfer\robert\thegame\
copy shpmke2w.exe s:\transfer\robert\thegame\


