#include "dosdefs.h"

//DEADCODE DAW 27/05/99 #ifdef _DEBUG
//DEADCODE DAW 27/05/99 void* __cdecl operator new(size_t nSize, char* lpszFileName, int nLine);
//DEADCODE DAW 27/05/99 #define THIS_FILE "3D:" __FILE__
//DEADCODE DAW 27/05/99 #define DEBUG_NEW new(THIS_FILE, __LINE__)
//DEADCODE DAW 27/05/99 #endif
//left in migland.h ? const int _altitudeScale=50;
#define IN_MIGLAND_CPP
#define	F_BATTLE
#include	"files.g"
#include "fileman.h"
#include "uniqueid.h"
#include	"bfnumber.h"

