//------------------------------------------------------------------------------
//Filename       maclib.h
//System         
//Author         Paul.   
//Date           Thu 6 Jul 1995
//Description    
//------------------------------------------------------------------------------
#ifndef	maclib_Included
#define	maclib_Included

#define	abs(n)	((n)<0 ? 0-(n) : (n))
#define sgn(n)	((n) ? (n)/abs((n)) : 0)


#endif
