//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by REdtBt.rc
//
#define IDS_REDTBT                      1
#define IDB_REDTBT                      1
#define IDS_REDTBT_PPG                  2
#define IDB_RCOMBOBUTTON                182
#define IDS_REDTBT_PPG_CAPTION          200
#define IDD_PROPPAGE_REDTBT             200
#define IDC_FONT_NUMBER                 202
#define IDI_RCOMBOBUTTON                204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
