


#define	T_NULL					0x0                
                   
//DeadCode RDH 19Feb98 #define	T_UID_AfAlPoulainville	0x0c7f
//DeadCode RDH 19Feb98 #define	T_UID_ToAlPoulainville	0x0a5f
//DeadCode RDH 19Feb98 #define	T_UID_AfAlVignacourt	0x0c7e
//DeadCode RDH 19Feb98 #define	T_UID_ToAlVignacourt	0x0a5e
//DeadCode RDH 19Feb98 #define	T_UID_AfAlCandas	0x0c7d
//DeadCode RDH 19Feb98 #define	T_UID_ToAlCandas	0x0a5d
//DeadCode RDH 19Feb98 #define	T_UID_AfCpVillersAuTerte	0x0c3f
//DeadCode RDH 19Feb98 #define	T_UID_ToCpVillersAuTerte	0x0a5c
//DeadCode RDH 19Feb98 #define	T_UID_AfCpRoucourt	0x0c3e
//DeadCode RDH 19Feb98 #define	T_UID_ToCpRoucourt	0x0a5b
//DeadCode RDH 19Feb98 #define	T_UID_AfCpDouai	0x0c3d
//DeadCode RDH 19Feb98 #define	T_UID_ToCpDouai	0x0a5a
//DeadCode RDH 19Feb98 #define	T_UID_AfCpGuesnain	0x0c3c
//DeadCode RDH 19Feb98 #define	T_UID_ToCpGuesnain	0x0a59
//DeadCode RDH 19Feb98 #define	T_UID_AfCpAulnoy	0x0c3b
//DeadCode RDH 19Feb98 #define	T_UID_ToCpAulnoy	0x0a58
//DeadCode RDH 19Feb98 #define	T_UID_AfCpAniche	0x0c3a
//DeadCode RDH 19Feb98 #define	T_UID_ToCpAniche	0x0a57
//DeadCode RDH 19Feb98 #define	T_UID_AfCpErchin	0x0c39
//DeadCode RDH 19Feb98 #define	T_UID_ToCpErchin	0x0a56
//DeadCode RDH 19Feb98 #define	T_UID_AfCpEmerchicourt	0x0c38
//DeadCode RDH 19Feb98 #define	T_UID_ToCpEmerchicourt	0x0a55
//DeadCode RDH 19Feb98 #define	T_UID_AfCpEswars	0x0c37
//DeadCode RDH 19Feb98 #define	T_UID_ToCpEswars	0x0a54
//DeadCode RDH 19Feb98 #define	T_UID_AfCpEstourmel	0x0c36
//DeadCode RDH 19Feb98 #define	T_UID_ToCpEstourmel	0x0a53
//DeadCode RDH 19Feb98 #define	T_UID_AfCpEpinoy	0x0c35
//DeadCode RDH 19Feb98 #define	T_UID_ToCpEpinoy	0x0a52
//DeadCode RDH 19Feb98 #define	T_UID_AfCpBevillers	0x0c34
//DeadCode RDH 19Feb98 #define	T_UID_ToCpBevillers	0x0a51
//DeadCode RDH 19Feb98 #define	T_UID_AfCpFlesquieres	0x0c33
//DeadCode RDH 19Feb98 #define	T_UID_ToCpFlesquieres	0x0a50
//DeadCode RDH 19Feb98 #define	T_UID_AfCpProville	0x0c32
//DeadCode RDH 19Feb98 #define	T_UID_ToCpProville	0x0a4f
//DeadCode RDH 19Feb98 #define	T_UID_AfCpAwoignt	0x0c31
//DeadCode RDH 19Feb98 #define	T_UID_ToCpAwoignt	0x0a4e
//DeadCode RDH 19Feb98 #define	T_UID_AfCpPronville	0x0c30
//DeadCode RDH 19Feb98 #define	T_UID_ToCpPronville	0x0a4d
//DeadCode RDH 19Feb98 #define	T_UID_AfCpRiencourt	0x0c2f
//DeadCode RDH 19Feb98 #define	T_UID_ToCpRiencourt	0x0a4c
//DeadCode RDH 19Feb98 #define	T_UID_AfAlMarieux	0x0c7c
//DeadCode RDH 19Feb98 #define	T_UID_ToAlMarieux	0x0a4b
//DeadCode RDH 19Feb98 #define	T_UID_AfAlBellevue	0x0c7b
//DeadCode RDH 19Feb98 #define	T_UID_ToAlBellevue	0x0a4a
//DeadCode RDH 19Feb98 #define	T_UID_AfAlFienvillers	0x0c7a
//DeadCode RDH 19Feb98 #define	T_UID_ToAlFienvillers	0x0a49
//DeadCode RDH 19Feb98 #define	T_UID_AfAlSavy	0x0c79
//DeadCode RDH 19Feb98 #define	T_UID_ToAlSavy	0x0a48
//DeadCode RDH 19Feb98 #define	T_UID_AfAlVertGaland	0x0c78
//DeadCode RDH 19Feb98 #define	T_UID_ToAlVertGaland	0x0a47
//DeadCode RDH 19Feb98 #define	T_UID_AfAlFilescampFarm	0x0c77
//DeadCode RDH 19Feb98 #define	T_UID_ToAlFilescampFarm	0x0a46
//DeadCode RDH 19Feb98 #define	T_UID_AfAlEtrun	0x0c76
//DeadCode RDH 19Feb98 #define	T_UID_ToAlEtrun	0x0a45
//DeadCode RDH 19Feb98 #define	T_UID_AfAlStEloi	0x0c75
//DeadCode RDH 19Feb98 #define	T_UID_ToAlStEloi	0x0a44
//DeadCode RDH 19Feb98 #define	T_UID_AfAlIzelLeHameau	0x0c74
//DeadCode RDH 19Feb98 #define	T_UID_ToAlIzelLeHameau	0x0a43
//DeadCode RDH 19Feb98 #define	T_UID_AfAlHauteVisee	0x0c73
//DeadCode RDH 19Feb98 #define	T_UID_ToAlHauteVisee	0x0a42
//DeadCode RDH 19Feb98 #define	T_UID_AfAlBertangles	0x0c72
//DeadCode RDH 19Feb98 #define	T_UID_ToAlBertangles	0x0a41
//DeadCode RDH 19Feb98 #define	T_UID_AfCpBalatre	0x0c2e
//DeadCode RDH 19Feb98 #define	T_UID_ToCpBalatre	0x0a40
//DeadCode RDH 19Feb98 #define	T_UID_AfCpVilleselve	0x0c2d
//DeadCode RDH 19Feb98 #define	T_UID_ToCpVilleselve	0x0a3f
//DeadCode RDH 19Feb98 #define	T_UID_AfAlBruay	0x0c71
//DeadCode RDH 19Feb98 #define	T_UID_ToAlBruay	0x0a3e
//DeadCode RDH 19Feb98 #define	T_UID_AfAlLozinghem	0x0c70
//DeadCode RDH 19Feb98 #define	T_UID_ToAlLozinghem	0x0a3d
//DeadCode RDH 19Feb98 #define	T_UID_AfAlHesdigneul	0x0c6f
//DeadCode RDH 19Feb98 #define	T_UID_ToAlHesdigneul	0x0a3c
//DeadCode RDH 19Feb98 #define	T_UID_AfAlVillersCagnicourt	0x0c6e
//DeadCode RDH 19Feb98 #define	T_UID_ToAlVillersCagnicourt	0x0a3b
//DeadCode RDH 19Feb98 #define	T_UID_AfCpCarnin	0x0c2c
//DeadCode RDH 19Feb98 #define	T_UID_ToCpCarnin	0x0a3a
//DeadCode RDH 19Feb98 #define	T_UID_AfCpProuvy	0x0c2b
//DeadCode RDH 19Feb98 #define	T_UID_ToCpProuvy	0x0a39
//DeadCode RDH 19Feb98 #define	T_UID_AfCpPhalempin	0x0c2a
//DeadCode RDH 19Feb98 #define	T_UID_ToCpPhalempin	0x0a38
//DeadCode RDH 19Feb98 #define	T_UID_AfCpCantin	0x0c29
//DeadCode RDH 19Feb98 #define	T_UID_ToCpCantin	0x0a37
//DeadCode RDH 19Feb98 #define	T_UID_AfAlBapaume	0x0c6d
//DeadCode RDH 19Feb98 #define	T_UID_ToAlBapaume	0x0a36
//DeadCode RDH 19Feb98 #define	T_UID_AfAlBouvincourt	0x0c6c
//DeadCode RDH 19Feb98 #define	T_UID_ToAlBouvincourt	0x0a35
//DeadCode RDH 19Feb98 #define	T_UID_AfCpGuise	0x0c28
//DeadCode RDH 19Feb98 #define	T_UID_ToCpGuise	0x0a34
//DeadCode RDH 19Feb98 #define	T_UID_AfAlLechelle	0x0c6b
//DeadCode RDH 19Feb98 #define	T_UID_ToAlLechelle	0x0a33
//DeadCode RDH 19Feb98 #define	T_UID_AfAlCachy	0x0c6a
//DeadCode RDH 19Feb98 #define	T_UID_ToAlCachy	0x0a32
//DeadCode RDH 19Feb98 #define	T_UID_AfAlCorcelles	0x0c69
//DeadCode RDH 19Feb98 #define	T_UID_ToAlCorcelles	0x0a31
//DeadCode RDH 19Feb98 #define	T_UID_AfAlAblainzevelle	0x0c68
//DeadCode RDH 19Feb98 #define	T_UID_ToAlAblainzevelle	0x0a30
//DeadCode RDH 19Feb98 #define	T_UID_AfAlMory	0x0c67
//DeadCode RDH 19Feb98 #define	T_UID_ToAlMory	0x0a2f
//DeadCode RDH 19Feb98 #define	T_UID_AfAlFlez	0x0c66
//DeadCode RDH 19Feb98 #define	T_UID_ToAlFlez	0x0a2e
//DeadCode RDH 19Feb98 #define	T_UID_AfAlEstreeBlanche	0x0c65
//DeadCode RDH 19Feb98 #define	T_UID_ToAlEstreeBlanche	0x0a2d
//DeadCode RDH 19Feb98 #define	T_UID_AfCpMonsEnChaussee	0x0c27
//DeadCode RDH 19Feb98 #define	T_UID_ToCpMonsEnChaussee	0x0a2c
//DeadCode RDH 19Feb98 #define	T_UID_AfCpLechelle	0x0c26
//DeadCode RDH 19Feb98 #define	T_UID_ToCpLechelle	0x0a2b
//DeadCode RDH 19Feb98 #define	T_UID_RhCpBapaume	0x0cbf
//DeadCode RDH 19Feb98 #define	T_UID_SdCpNEAlbert	0x0cbe
//DeadCode RDH 19Feb98 #define	T_UID_AfCpBapaume	0x0c25
//DeadCode RDH 19Feb98 #define	T_UID_ToCpBapaume	0x0a2a
//DeadCode RDH 19Feb98 #define	T_UID_AfAlLavieville	0x0c64
//DeadCode RDH 19Feb98 #define	T_UID_ToAlLavieville	0x0a29
//DeadCode RDH 19Feb98 #define	T_UID_AfAlBaizieux	0x0c63
//DeadCode RDH 19Feb98 #define	T_UID_ToAlBaizieux	0x0a28
//DeadCode RDH 19Feb98 #define	T_UID_AfAlLealvillers	0x0c62
//DeadCode RDH 19Feb98 #define	T_UID_ToAlLealvillers	0x0a27
//DeadCode RDH 19Feb98 #define	T_UID_AfAlBoiryStMartin	0x0c61
//DeadCode RDH 19Feb98 #define	T_UID_ToAlBoiryStMartin	0x0a26
//DeadCode RDH 19Feb98 #define	T_UID_AfCpCappy	0x0c24
//DeadCode RDH 19Feb98 #define	T_UID_ToCpCappy	0x0a25
//DeadCode RDH 19Feb98 #define	T_UID_AfCpArs	0x0c23
//DeadCode RDH 19Feb98 #define	T_UID_ToCpArs	0x0a24
//DeadCode RDH 19Feb98 #define	T_UID_AfCpGiraumont	0x0c22
//DeadCode RDH 19Feb98 #define	T_UID_ToCpGiraumont	0x0a23
//DeadCode RDH 19Feb98 #define	T_UID_AfCpTichemont	0x0c21
//DeadCode RDH 19Feb98 #define	T_UID_ToCpTichemont	0x0a22
//DeadCode RDH 19Feb98 #define	T_UID_AfCpMercyLeHaute	0x0c20
//DeadCode RDH 19Feb98 #define	T_UID_ToCpMercyLeHaute	0x0a21
//DeadCode RDH 19Feb98 #define	T_UID_AfCpMartincourt	0x0c1f
//DeadCode RDH 19Feb98 #define	T_UID_ToCpMartincourt	0x0a20
//DeadCode RDH 19Feb98 #define	T_UID_AfCpStenay	0x0c1e
//DeadCode RDH 19Feb98 #define	T_UID_ToCpStenay	0x0a1f
//DeadCode RDH 19Feb98 #define	T_UID_AfCpFrescaty	0x0c1d
//DeadCode RDH 19Feb98 #define	T_UID_ToCpFrescaty	0x0a1e
//DeadCode RDH 19Feb98 #define	T_UID_AfCpVancouleurs	0x0c60
//DeadCode RDH 19Feb98 #define	T_UID_ToCpVancouleurs	0x0a1d
//DeadCode RDH 19Feb98 #define	T_UID_AfCpMarsLaTour	0x0c1c
//DeadCode RDH 19Feb98 #define	T_UID_ToCpMarsLaTour	0x0a1c
//DeadCode RDH 19Feb98 #define	T_UID_AfCpPrullinHigny	0x0c1b
//DeadCode RDH 19Feb98 #define	T_UID_ToCpPrullinHigny	0x0a1b
//DeadCode RDH 19Feb98 #define	T_UID_AfCpMarville	0x0c1a
//DeadCode RDH 19Feb98 #define	T_UID_ToCpMarville	0x0a1a
//DeadCode RDH 19Feb98 #define	T_UID_AlTdTrescault	0x0cff
//DeadCode RDH 19Feb98 #define	T_UID_AlTdHavrincourtWd	0x0cfe
//DeadCode RDH 19Feb98 #define	T_UID_AlBnTrescault	0x0dff
//DeadCode RDH 19Feb98 #define	T_UID_AlBnHavrincourtWd	0x0dfe
//DeadCode RDH 19Feb98 #define	T_UID_AlAfHermies	0x0c5f
//DeadCode RDH 19Feb98 #define	T_UID_AtSWFlesquieres	0x0b7e
//DeadCode RDH 19Feb98 #define	T_UID_AtSFlesquieres	0x0b7d
//DeadCode RDH 19Feb98 #define	T_UID_AtFlesquieres	0x0b7c
//DeadCode RDH 19Feb98 #define	T_UID_AtWFlesquieres	0x0b7b
//DeadCode RDH 19Feb98 #define	T_UID_AtNWFlesquieres	0x0b7a
//DeadCode RDH 19Feb98 #define	T_UID_AtNFlesquieres	0x0b79
//DeadCode RDH 19Feb98 #define	T_UID_AtGraincourt	0x0b78
//DeadCode RDH 19Feb98 #define	T_UID_AtSEGraincourt	0x0b77
//DeadCode RDH 19Feb98 #define	T_UID_AtOrival	0x0b76
//DeadCode RDH 19Feb98 #define	T_UID_AtEOrival	0x0b75
//DeadCode RDH 19Feb98 #define	T_UID_AtSRibecourt	0x0b74
//DeadCode RDH 19Feb98 #define	T_UID_AtWRibecourt	0x0b73
//DeadCode RDH 19Feb98 #define	T_UID_AtNRibecourt	0x0b72
//DeadCode RDH 19Feb98 #define	T_UID_AtRibecourtLine	0x0b71
//DeadCode RDH 19Feb98 #define	T_UID_AtAnneux	0x0b70
//DeadCode RDH 19Feb98 #define	T_UID_AtFontaine	0x0b6f
//DeadCode RDH 19Feb98 #define	T_UID_AtBourlonWd	0x0b6e
//DeadCode RDH 19Feb98 #define	T_UID_AtSCantaing	0x0b6d
//DeadCode RDH 19Feb98 #define	T_UID_AtSWCantaing	0x0b6c
//DeadCode RDH 19Feb98 #define	T_UID_AtNPremy	0x0b6b
//DeadCode RDH 19Feb98 #define	T_UID_AtNNMarcoing	0x0b6a
//DeadCode RDH 19Feb98 #define	T_UID_AtSNoyelles	0x0b69
//DeadCode RDH 19Feb98 #define	T_UID_AtNoyelles	0x0b68
//DeadCode RDH 19Feb98 #define	T_UID_AtEEMarcoing	0x0b67
//DeadCode RDH 19Feb98 #define	T_UID_AtWMarcoing	0x0b66
//DeadCode RDH 19Feb98 #define	T_UID_AtCMarcoing	0x0b65
//DeadCode RDH 19Feb98 #define	T_UID_AtEENoyelles	0x0b64
//DeadCode RDH 19Feb98 #define	T_UID_AtEECantaing	0x0b63
//DeadCode RDH 19Feb98 #define	T_UID_AtEENCantaing	0x0b62
//DeadCode RDH 19Feb98 #define	T_UID_AtECantaing	0x0b61
//DeadCode RDH 19Feb98 #define	T_UID_AtEFontaine	0x0b60
//DeadCode RDH 19Feb98 #define	T_UID_AtNECantaing	0x0b5f
//DeadCode RDH 19Feb98 #define	T_UID_ChAlBertangles	0x0d7f
//DeadCode RDH 19Feb98 #define	T_UID_CvNtOppy	0x09ff
//DeadCode RDH 19Feb98 #define	T_UID_BlCpOppy	0x0dbf
//DeadCode RDH 19Feb98 #define	T_UID_BnCpOppy	0x063f
//DeadCode RDH 19Feb98 #define	T_UID_CvNtNeuvireuil	0x09fe
//DeadCode RDH 19Feb98 #define	T_UID_BtCpNeuvireuil	0x0b5e
//DeadCode RDH 19Feb98 #define	T_UID_RcCpFresnes	0x0a7f
//DeadCode RDH 19Feb98 #define	T_UID_CvNtFresnes	0x09fd
//DeadCode RDH 19Feb98 #define	T_UID_BtCpPlouvain	0x0b5d
//DeadCode RDH 19Feb98 #define	T_UID_CvNtPlouvain	0x09fc
//DeadCode RDH 19Feb98 #define	T_UID_CvNtGuemappe	0x09fb
//DeadCode RDH 19Feb98 #define	T_UID_AdCpWVis	0x0cbc
//DeadCode RDH 19Feb98 #define	T_UID_AdCpWBoiryND	0x0cbb
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMonchy	0x09fa
//DeadCode RDH 19Feb98 #define	T_UID_RcNtBoiryND	0x0a7e
//DeadCode RDH 19Feb98 #define	T_UID_CvNtBoiryND	0x09f9
//DeadCode RDH 19Feb98 #define	T_UID_AdCpSWSaillyOstrevent	0x0cba
//DeadCode RDH 19Feb98 #define	T_UID_AdCpSEPelves	0x0cb9
//DeadCode RDH 19Feb98 #define	T_UID_SdCpESaillyOstrevent	0x0cb8
//DeadCode RDH 19Feb98 #define	T_UID_CvNtPelves	0x09f8
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRoeux	0x09f7
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRoeuxChemical	0x09f6
//DeadCode RDH 19Feb98 #define	T_UID_BlCpVis	0x0dbe
//DeadCode RDH 19Feb98 #define	T_UID_BnCpVis	0x063e
//DeadCode RDH 19Feb98 #define	T_UID_CvNtDury	0x09f5
//DeadCode RDH 19Feb98 #define	T_UID_CvNtVis	0x09f4
//DeadCode RDH 19Feb98 #define	T_UID_BlCpremy	0x0dbd
//DeadCode RDH 19Feb98 #define	T_UID_BnCpremy	0x063d
//DeadCode RDH 19Feb98 #define	T_UID_BlCpremy1	0x0dbc
//DeadCode RDH 19Feb98 #define	T_UID_BnCpremy1	0x063c
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRemy	0x09f3
//DeadCode RDH 19Feb98 #define	T_UID_CvNtCherisy	0x09f2
//DeadCode RDH 19Feb98 #define	T_UID_CvNtCagnicourt	0x09f1
//DeadCode RDH 19Feb98 #define	T_UID_CvNtFontaine	0x09f0
//DeadCode RDH 19Feb98 #define	T_UID_BtCpCagnicourt	0x0b5c
//DeadCode RDH 19Feb98 #define	T_UID_BtCpCagnicourt1	0x0b5b
//DeadCode RDH 19Feb98 #define	T_UID_SdCpCagnicourt	0x0cb7
//DeadCode RDH 19Feb98 #define	T_UID_CvNtPeronne	0x09ef
//DeadCode RDH 19Feb98 #define	T_UID_BrNtOffoy	0x05bf
//DeadCode RDH 19Feb98 #define	T_UID_RhAlNesle	0x0cb6
//DeadCode RDH 19Feb98 #define	T_UID_BrNtPargny	0x05be
//DeadCode RDH 19Feb98 #define	T_UID_BrNtHam	0x05bd
//DeadCode RDH 19Feb98 #define	T_UID_AdCpSHaucourt	0x0cb5
//DeadCode RDH 19Feb98 #define	T_UID_SdCpHaucourt	0x0cb4
//DeadCode RDH 19Feb98 #define	T_UID_AdCpSWHaucourt	0x0cb3
//DeadCode RDH 19Feb98 #define	T_UID_CvNtHaucourt	0x09ee
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRouvroy	0x09ed
//DeadCode RDH 19Feb98 #define	T_UID_CvNtFresnoy	0x09ec
//DeadCode RDH 19Feb98 #define	T_UID_BlCpERiencourt	0x0dbb
//DeadCode RDH 19Feb98 #define	T_UID_BnCpERiencourt	0x063b
//DeadCode RDH 19Feb98 #define	T_UID_BlCpAcheville	0x0dba
//DeadCode RDH 19Feb98 #define	T_UID_BnCpAcheville	0x063a
//DeadCode RDH 19Feb98 #define	T_UID_BtCpAcheville	0x0b5a
//DeadCode RDH 19Feb98 #define	T_UID_CvNtAcheville	0x09eb
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRiencourt	0x09ea
//DeadCode RDH 19Feb98 #define	T_UID_CvNtQueant	0x09e9
//DeadCode RDH 19Feb98 #define	T_UID_BtCpRemy	0x0b59
//DeadCode RDH 19Feb98 #define	T_UID_BtCpNoyelles	0x0b58
//DeadCode RDH 19Feb98 #define	T_UID_CvNtGavrelle	0x09e8
//DeadCode RDH 19Feb98 #define	T_UID_CvNtDrocourt	0x09e7
//DeadCode RDH 19Feb98 #define	T_UID_BlCpHendecourt	0x0db9
//DeadCode RDH 19Feb98 #define	T_UID_BnCpHendecourt	0x0639
//DeadCode RDH 19Feb98 #define	T_UID_CvNtLeCatelet	0x09e6
//DeadCode RDH 19Feb98 #define	T_UID_AdCpWArleux	0x0cb2
//DeadCode RDH 19Feb98 #define	T_UID_CvNtArleux	0x09e5
//DeadCode RDH 19Feb98 #define	T_UID_AdCpNrEArleux	0x0cb1
//DeadCode RDH 19Feb98 #define	T_UID_SdCpArleux	0x0cb0
//DeadCode RDH 19Feb98 #define	T_UID_AdCpNBrebieres	0x0caf
//DeadCode RDH 19Feb98 #define	T_UID_AdCpNNBrebieres	0x0cae
//DeadCode RDH 19Feb98 #define	T_UID_CvNtBrebieres	0x09e4
//DeadCode RDH 19Feb98 #define	T_UID_AdCpSWVitry	0x0cad
//DeadCode RDH 19Feb98 #define	T_UID_CvNtVitry	0x09e3
//DeadCode RDH 19Feb98 #define	T_UID_RcCpVitry	0x0a7d
//DeadCode RDH 19Feb98 #define	T_UID_AdCpNWVitry	0x0cac
//DeadCode RDH 19Feb98 #define	T_UID_AdCpNVitry	0x0cab
//DeadCode RDH 19Feb98 #define	T_UID_CvNtAuby	0x09e2
//DeadCode RDH 19Feb98 #define	T_UID_SdCpAuby	0x0caa
//DeadCode RDH 19Feb98 #define	T_UID_CvNtLourches	0x09e1
//DeadCode RDH 19Feb98 #define	T_UID_CcCpDenain	0x0d3e
//DeadCode RDH 19Feb98 #define	T_UID_CvNtDenain	0x09e0
//DeadCode RDH 19Feb98 #define	T_UID_CvNtValenciennes	0x09df
//DeadCode RDH 19Feb98 #define	T_UID_CcCpAniche	0x0d3d
//DeadCode RDH 19Feb98 #define	T_UID_CvNtAniche	0x09de
//DeadCode RDH 19Feb98 #define	T_UID_SdCpLourches	0x0ca9
//DeadCode RDH 19Feb98 #define	T_UID_CvNtLewarde	0x09dd
//DeadCode RDH 19Feb98 #define	T_UID_CvNtCantin	0x09dc
//DeadCode RDH 19Feb98 #define	T_UID_RcCpCantin	0x0a7c
//DeadCode RDH 19Feb98 #define	T_UID_AdCpCantin	0x0ca8
//DeadCode RDH 19Feb98 #define	T_UID_SdCpCantin	0x0ca7
//DeadCode RDH 19Feb98 #define	T_UID_CvNtErchin	0x09db
//DeadCode RDH 19Feb98 #define	T_UID_RcCpErchin	0x0a7b
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRoucourt	0x09da
//DeadCode RDH 19Feb98 #define	T_UID_CHCpRoucourt	0x0d3c
//DeadCode RDH 19Feb98 #define	T_UID_BnCpRoucourt	0x0638
//DeadCode RDH 19Feb98 #define	T_UID_CvNtDouai	0x09d9
//DeadCode RDH 19Feb98 #define	T_UID_CvNtLagnicourt	0x09d8
//DeadCode RDH 19Feb98 #define	T_UID_CvNtDemicourt	0x09d7
//DeadCode RDH 19Feb98 #define	T_UID_HQCpRecourt	0x0d3b
//DeadCode RDH 19Feb98 #define	T_UID_CvNtSaillyLeSec	0x09d6
//DeadCode RDH 19Feb98 #define	T_UID_CvNtCachy	0x09d5
//DeadCode RDH 19Feb98 #define	T_UID_BtAlBretonneux	0x0bff
//DeadCode RDH 19Feb98 #define	T_UID_CvNtLeHamel	0x09d4
//DeadCode RDH 19Feb98 #define	T_UID_CvNtLongueau	0x09d3
//DeadCode RDH 19Feb98 #define	T_UID_CvNtHangard	0x09d2
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMametz	0x09d1
//DeadCode RDH 19Feb98 #define	T_UID_CvNtContalmaison	0x09d0
//DeadCode RDH 19Feb98 #define	T_UID_CvNtThiepval	0x09cf
//DeadCode RDH 19Feb98 #define	T_UID_CvNtBeaumontHamel	0x09ce
//DeadCode RDH 19Feb98 #define	T_UID_CvNtCappy	0x09cd
//DeadCode RDH 19Feb98 #define	T_UID_SdCpCappy	0x0cbd
//DeadCode RDH 19Feb98 #define	T_UID_ChCpCappy	0x0d3f
//DeadCode RDH 19Feb98 #define	T_UID_CvNtCerisy	0x09cc
//DeadCode RDH 19Feb98 #define	T_UID_BrNtCerisy	0x05bc
//DeadCode RDH 19Feb98 #define	T_UID_BtCpCerisy	0x0b7f
//DeadCode RDH 19Feb98 #define	T_UID_CvNtVillersBretonneux	0x09cb
//DeadCode RDH 19Feb98 #define	T_UID_CvNtCorbie	0x09ca
//DeadCode RDH 19Feb98 #define	T_UID_CvNtFricourt	0x09c9
//DeadCode RDH 19Feb98 #define	T_UID_CvNtAlbert	0x09c8
//DeadCode RDH 19Feb98 #define	T_UID_CvNtOrchies	0x09c7
//DeadCode RDH 19Feb98 #define	T_UID_AfAlTreizennes	0x0c5e
//DeadCode RDH 19Feb98 #define	T_UID_ToAlTreizennes	0x0a19
//DeadCode RDH 19Feb98 #define	T_UID_AfAlSoncamps	0x0c5d
//DeadCode RDH 19Feb98 #define	T_UID_ToAlSoncamps	0x0a18
//DeadCode RDH 19Feb98 #define	T_UID_CvNtAmiens	0x09c6
//DeadCode RDH 19Feb98 #define	T_UID_CvNtDoullens	0x09c5
//DeadCode RDH 19Feb98 #define	T_UID_BlCpMoeuvres	0x0db8
//DeadCode RDH 19Feb98 #define	T_UID_BnCpMoeuvres	0x0637
//DeadCode RDH 19Feb98 #define	T_UID_BrNtMarcoing	0x05bb
//DeadCode RDH 19Feb98 #define	T_UID_BlCpFlesquieres	0x0db7
//DeadCode RDH 19Feb98 #define	T_UID_BnCpFlesquieres	0x0636
//DeadCode RDH 19Feb98 #define	T_UID_ChCpHavrincourt	0x0a17
//DeadCode RDH 19Feb98 #define	T_UID_BrNtMasnieres	0x05ba
//DeadCode RDH 19Feb98 #define	T_UID_BrNtNoyelles	0x05b9
//DeadCode RDH 19Feb98 #define	T_UID_BrNtCantaing	0x05b8
//DeadCode RDH 19Feb98 #define	T_UID_BrNtFontaine	0x05b7
//DeadCode RDH 19Feb98 #define	T_UID_ChNtFlesquieres	0x0d3a
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMarquion	0x09c4
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRibecourt	0x09c3
//DeadCode RDH 19Feb98 #define	T_UID_CvNtGraincourt	0x09c2
//DeadCode RDH 19Feb98 #define	T_UID_CvNtFlesquieres	0x09c1
//DeadCode RDH 19Feb98 #define	T_UID_CvNtAnneux	0x09c0
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMoeuvres	0x09bf
//DeadCode RDH 19Feb98 #define	T_UID_CvNtFontaineND	0x09be
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMarcoing	0x09bd
//DeadCode RDH 19Feb98 #define	T_UID_CvNtHavrincourt	0x09bc
//DeadCode RDH 19Feb98 #define	T_UID_CvNtTresault	0x09bb
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMasniere	0x09ba
//DeadCode RDH 19Feb98 #define	T_UID_CvNtNoyelles	0x09b9
//DeadCode RDH 19Feb98 #define	T_UID_CvNtCambrai	0x09b8
//DeadCode RDH 19Feb98 #define	T_UID_CvNtStQuentin	0x09b7
//DeadCode RDH 19Feb98 #define	T_UID_CvNtFarbus	0x09b6
//DeadCode RDH 19Feb98 #define	T_UID_CvNtBailleul	0x09b5
//DeadCode RDH 19Feb98 #define	T_UID_WdNtBertincourt	0x09b4
//DeadCode RDH 19Feb98 #define	T_UID_AdCpSOisy	0x0ca6
//DeadCode RDH 19Feb98 #define	T_UID_AdCpSEOisy	0x0ca5
//DeadCode RDH 19Feb98 #define	T_UID_AdCpEcourtStQ	0x0ca4
//DeadCode RDH 19Feb98 #define	T_UID_AdCpSaucyLestree	0x0ca3
//DeadCode RDH 19Feb98 #define	T_UID_CVNtEpinoy	0x09b3
//DeadCode RDH 19Feb98 #define	T_UID_AdCpRumaucourt	0x0ca2
//DeadCode RDH 19Feb98 #define	T_UID_SdCpOisy	0x0ca1
//DeadCode RDH 19Feb98 #define	T_UID_AdCpSauchyCauchy	0x0ca0
//DeadCode RDH 19Feb98 #define	T_UID_BtCpInchy	0x0b57
//DeadCode RDH 19Feb98 #define	T_UID_CvNtInchy	0x09b2
//DeadCode RDH 19Feb98 #define	T_UID_SdCpEMarquion	0x0c9f
//DeadCode RDH 19Feb98 #define	T_UID_RhCpMarquion	0x0c9e
//DeadCode RDH 19Feb98 #define	T_UID_AdCpMarquion	0x0c9d
//DeadCode RDH 19Feb98 #define	T_UID_BtCpFlesquieres	0x0b56
//DeadCode RDH 19Feb98 #define	T_UID_BtCpAnneux	0x0b55
//DeadCode RDH 19Feb98 #define	T_UID_BtCpBourlonWd	0x0b54
//DeadCode RDH 19Feb98 #define	T_UID_BrCpRiqueval	0x05b6
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRiqueval	0x09b1
//DeadCode RDH 19Feb98 #define	T_UID_BlCpLeCatelet0	0x0db6
//DeadCode RDH 19Feb98 #define	T_UID_BnCpLeCatelet0	0x0635
//DeadCode RDH 19Feb98 #define	T_UID_BlCpLeCatelet1	0x0db5
//DeadCode RDH 19Feb98 #define	T_UID_BnCpLeCatelet1	0x0634
//DeadCode RDH 19Feb98 #define	T_UID_BlCpLeCatelet2	0x0db4
//DeadCode RDH 19Feb98 #define	T_UID_BnCpLeCatelet2	0x0633
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRonssoy	0x09b0
//DeadCode RDH 19Feb98 #define	T_UID_CvNtSancourt	0x09af
//DeadCode RDH 19Feb98 #define	T_UID_CvNtHermies	0x09ae
//DeadCode RDH 19Feb98 #define	T_UID_BtCpMasniere	0x0b53
//DeadCode RDH 19Feb98 #define	T_UID_BlCpRumilly0	0x0db3
//DeadCode RDH 19Feb98 #define	T_UID_BnCpRumilly0	0x0632
//DeadCode RDH 19Feb98 #define	T_UID_BlCpRumilly1	0x0db2
//DeadCode RDH 19Feb98 #define	T_UID_BnCpRumilly1	0x0631
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRumilly	0x09ad
//DeadCode RDH 19Feb98 #define	T_UID_BlCpRumilly2	0x0db1
//DeadCode RDH 19Feb98 #define	T_UID_BnCpRumilly2	0x0630
//DeadCode RDH 19Feb98 #define	T_UID_BtCpBantouzelle	0x0b52
//DeadCode RDH 19Feb98 #define	T_UID_CvNtBantouzelle	0x09ac
//DeadCode RDH 19Feb98 #define	T_UID_SdCpBouchain	0x0c9c
//DeadCode RDH 19Feb98 #define	T_UID_BrNtStChrist	0x05b5
//DeadCode RDH 19Feb98 #define	T_UID_BrNtBrie	0x05b4
//DeadCode RDH 19Feb98 #define	T_UID_CvNtLongueval	0x09ab
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMartinpuich	0x09aa
//DeadCode RDH 19Feb98 #define	T_UID_CvNtBapaume	0x09a9
//DeadCode RDH 19Feb98 #define	T_UID_CvNtAvion	0x09a8
//DeadCode RDH 19Feb98 #define	T_UID_CvNtLens	0x09a7
//DeadCode RDH 19Feb98 #define	T_UID_BlCpMericourt	0x0db0
//DeadCode RDH 19Feb98 #define	T_UID_BnCpMericourt	0x062f
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMericourt	0x09a6
//DeadCode RDH 19Feb98 #define	T_UID_BtCpMericourt	0x0b51
//DeadCode RDH 19Feb98 #define	T_UID_BwCpFontaine	0x0a16
//DeadCode RDH 19Feb98 #define	T_UID_BlCpBoiryNotreDame	0x0daf
//DeadCode RDH 19Feb98 #define	T_UID_BnCpBoiryNotreDame	0x062e
//DeadCode RDH 19Feb98 #define	T_UID_BwCpRoeux	0x0a15
//DeadCode RDH 19Feb98 #define	T_UID_SaCpLens	0x0c9b
//DeadCode RDH 19Feb98 #define	T_UID_CvNtBoursies	0x09a5
//DeadCode RDH 19Feb98 #define	T_UID_AdCpMonchy	0x0c9a
//DeadCode RDH 19Feb98 #define	T_UID_CvNtArras	0x09a4
//DeadCode RDH 19Feb98 #define	T_UID_CvNtVerdun	0x09a3
//DeadCode RDH 19Feb98 #define	T_UID_CvNtExermont	0x0a14
//DeadCode RDH 19Feb98 #define	T_UID_CvNtStenay	0x09a2
//DeadCode RDH 19Feb98 #define	T_UID_BrNtAquaduct	0x05b3	/*0x0c19*/
//DeadCode RDH 19Feb98 #define	T_UID_BlCpGoin0	0x0dae
//DeadCode RDH 19Feb98 #define	T_UID_BnCpGoin0	0x062d
//DeadCode RDH 19Feb98 #define	T_UID_CvNtGoin	0x09a1
//DeadCode RDH 19Feb98 #define	T_UID_BlCpGoin1	0x0dad
//DeadCode RDH 19Feb98 #define	T_UID_BnCpGoin1	0x062c
//DeadCode RDH 19Feb98 #define	T_UID_BlCpMarieulles	0x0dac
//DeadCode RDH 19Feb98 #define	T_UID_BnCpMarieulles	0x062b
//DeadCode RDH 19Feb98 #define	T_UID_CvNtThionville	0x09a0
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMontmedy	0x099f
//DeadCode RDH 19Feb98 #define	T_UID_CvNtDunsurMeuse	0x099e
//DeadCode RDH 19Feb98 #define	T_UID_CvNtStJuvin	0x099d
//DeadCode RDH 19Feb98 #define	T_UID_CvNtCommercy	0x099c
//DeadCode RDH 19Feb98 #define	T_UID_CvNtXivray	0x099b
//DeadCode RDH 19Feb98 #define	T_UID_CvNtSeicheprey	0x099a
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMontsec	0x0999
//DeadCode RDH 19Feb98 #define	T_UID_CvNtSouilly	0x0998
//DeadCode RDH 19Feb98 #define	T_UID_CvNtDouaumont	0x0997
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMontFaucon	0x0996
//DeadCode RDH 19Feb98 #define	T_UID_CvNtGrandPre	0x0995
//DeadCode RDH 19Feb98 #define	T_UID_CvNtBuzancy	0x0994
//DeadCode RDH 19Feb98 #define	T_UID_BlCpStGeorges	0x0dab
//DeadCode RDH 19Feb98 #define	T_UID_BnCpStGeorges	0x062a
//DeadCode RDH 19Feb98 #define	T_UID_CvNtBrieulles	0x0993
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMalleloy	0x0992
//DeadCode RDH 19Feb98 #define	T_UID_CvNtArnaville	0x0991
//DeadCode RDH 19Feb98 #define	T_UID_CvNtChambley	0x0990
//DeadCode RDH 19Feb98 #define	T_UID_CvNtVigneulles	0x098f
//DeadCode RDH 19Feb98 #define	T_UID_CvNtConsenvoye	0x098e
//DeadCode RDH 19Feb98 #define	T_UID_CvNtDamvillers	0x098d
//DeadCode RDH 19Feb98 #define	T_UID_CvNtSivrysurMeuse	0x098c
//DeadCode RDH 19Feb98 #define	T_UID_CvNtRomagne	0x098b
//DeadCode RDH 19Feb98 #define	T_UID_BrNtBethencourt	0x05b2
//DeadCode RDH 19Feb98 #define	T_UID_BlCpMontfaucon	0x0daa
//DeadCode RDH 19Feb98 #define	T_UID_BnCpMontfaucon	0x0629
//DeadCode RDH 19Feb98 #define	T_UID_BlCpNantillois	0x0da9
//DeadCode RDH 19Feb98 #define	T_UID_BnCpNantillois	0x0628
//DeadCode RDH 19Feb98 #define	T_UID_BlCpRomagne	0x0da8
//DeadCode RDH 19Feb98 #define	T_UID_BnCpRomagne	0x0627
//DeadCode RDH 19Feb98 #define	T_UID_CvNtToul	0x098a
//DeadCode RDH 19Feb98 #define	T_UID_AfAlEToulBIAF	0x0c5c
//DeadCode RDH 19Feb98 #define	T_UID_ToAlEToulBIAF	0x0a12
//DeadCode RDH 19Feb98 #define	T_UID_AfAlEToul	0x0c5b
//DeadCode RDH 19Feb98 #define	T_UID_ToAlEToul	0x0a11
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMetz	0x0989
//DeadCode RDH 19Feb98 #define	T_UID_BtAlBeaumont	0x0bfe
//DeadCode RDH 19Feb98 #define	T_UID_CvNtBeaumont	0x0988
//DeadCode RDH 19Feb98 #define	T_UID_CvNtPontMousson	0x0987
//DeadCode RDH 19Feb98 #define	T_UID_CvNtStMihiel	0x0986
//DeadCode RDH 19Feb98 #define	T_UID_CvNtThiaucourt	0x0985
//DeadCode RDH 19Feb98 #define	T_UID_Varneville	0x0a13
//DeadCode RDH 19Feb98 #define	T_UID_CvNtLamorVille	0x0984
//DeadCode RDH 19Feb98 #define	T_UID_CvNtStRemy	0x0983
//DeadCode RDH 19Feb98 #define	T_UID_CvNtFresnes2	0x0982
//DeadCode RDH 19Feb98 #define	T_UID_AfAlLuneville	0x0c5a
//DeadCode RDH 19Feb98 #define	T_UID_ToAlLuneville	0x0a10
//DeadCode RDH 19Feb98 #define	T_UID_CvNtConflans	0x0981
//DeadCode RDH 19Feb98 #define	T_UID_AfAlErize	0x0c59
//DeadCode RDH 19Feb98 #define	T_UID_ToAlErize	0x0a0f
//DeadCode RDH 19Feb98 #define	T_UID_BlCpDoulcon0	0x0da7
//DeadCode RDH 19Feb98 #define	T_UID_BnCpDoulcon0	0x0626
//DeadCode RDH 19Feb98 #define	T_UID_BlCpDoulcon1	0x0da6
//DeadCode RDH 19Feb98 #define	T_UID_BnCpDoulcon1	0x0625
//DeadCode RDH 19Feb98 #define	T_UID_BlCpDoulcon2	0x0da5
//DeadCode RDH 19Feb98 #define	T_UID_BnCpDoulcon2	0x0624
//DeadCode RDH 19Feb98 #define	T_UID_BlCpDun0	0x0da4
//DeadCode RDH 19Feb98 #define	T_UID_BnCpDun0	0x0623
//DeadCode RDH 19Feb98 #define	T_UID_BlCpSivrysurMeuse0	0x0da3
//DeadCode RDH 19Feb98 #define	T_UID_BnCpSivrysurMeuse0	0x0622
//DeadCode RDH 19Feb98 #define	T_UID_BlCpSivrysurMeuse1	0x0da2
//DeadCode RDH 19Feb98 #define	T_UID_BnCpSivrysurMeuse1	0x0621
//DeadCode RDH 19Feb98 #define	T_UID_BlCpSivrysurMeuse2	0x0da1
//DeadCode RDH 19Feb98 #define	T_UID_BnCpSivrysurMeuse2	0x0620
//DeadCode RDH 19Feb98 #define	T_UID_BlCpDamvillers0	0x0da0
//DeadCode RDH 19Feb98 #define	T_UID_BnCpDamvillers0	0x061f
//DeadCode RDH 19Feb98 #define	T_UID_BlCpDamvillers1	0x0d9f
//DeadCode RDH 19Feb98 #define	T_UID_BnCpDamvillers1	0x061e
//DeadCode RDH 19Feb98 #define	T_UID_BlCpDamvillers2	0x0d9e
//DeadCode RDH 19Feb98 #define	T_UID_BnCpDamvillers2	0x061d
//DeadCode RDH 19Feb98 #define	T_UID_CvNtMarville	0x0980
//DeadCode RDH 19Feb98 #define	T_UID_CvNtNancy	0x097f
//DeadCode RDH 19Feb98 #define	T_UID_CvNtApremont	0x097e
//DeadCode RDH 19Feb98 #define	T_UID_CvNtFoug	0x097d
//DeadCode RDH 19Feb98 #define	T_UID_CvNtFlirey	0x097c
//DeadCode RDH 19Feb98 #define	T_UID_BlCpAincreville0	0x0d9d
//DeadCode RDH 19Feb98 #define	T_UID_BnCpAincreville0	0x061c
//DeadCode RDH 19Feb98 #define	T_UID_BlCpLamorville	0x0d9c
//DeadCode RDH 19Feb98 #define	T_UID_BnCpLamorville	0x061b
//DeadCode RDH 19Feb98 #define	T_UID_BlCpVarneville	0x0d9b
//DeadCode RDH 19Feb98 #define	T_UID_BnCpVarneville	0x061a
//DeadCode RDH 19Feb98 #define	T_UID_AfCpThiaucourt	0x0c19
//DeadCode RDH 19Feb98 #define	T_UID_ToCpThiaucourt	0x0a0e
//DeadCode RDH 19Feb98 #define	T_UID_BlCp3Fingers1	0x0d9a
//DeadCode RDH 19Feb98 #define	T_UID_BnCp3Fingers1	0x0619
//DeadCode RDH 19Feb98 #define	T_UID_BlCp3Fingers0	0x0d99
//DeadCode RDH 19Feb98 #define	T_UID_BnCp3Fingers0	0x0618
//DeadCode RDH 19Feb98 #define	T_UID_BlCp3Fingers2	0x0d98
//DeadCode RDH 19Feb98 #define	T_UID_BnCp3Fingers2	0x0617
//DeadCode RDH 19Feb98 #define	T_UID_AfAlExermont	0x0c58
//DeadCode RDH 19Feb98 #define	T_UID_ToAlExermont	0x0a0d
//DeadCode RDH 19Feb98 #define	T_UID_BlAlExermont	0x0dfd
//DeadCode RDH 19Feb98 #define	T_UID_BnAlExermont	0x0616
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_AFEnemy	0x0c17
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_Drums	0x05b1
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_StaffCar	0x027d
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_JournoCar	0x027b
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_BFSOPROTECTTROOPS_Item00	0x0a0c
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_AlTroopsSaintMihiel	0x0bfd
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_ChooChoo_Item01	0x0276
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_StraffeEscortTroops_P1	0x0a0b
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_ArtEscort_P1	0x0a0a
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_StraffeEscortTroops_P2	0x0a09
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_ArtEscort_P2	0x0a08
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_BourlonWoodTanks	0x01c6
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_BourlonWoodEndTanks	0x01c5
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_MarcoingTanks	0x01c4
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_MarcoingEndTanks	0x01c3
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_CantaingTanks	0x01c2
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_CantaingEndTanks	0x01c1
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_NoyellesTanks	0x01c0
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_NoyellesEndTanks	0x01bf
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_TurkeyShootCP00	0x04f1
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_BritishNoyellesTanks	0x0ffa
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_BritishTrucks	0x0bfc
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_OneOnOneGerm01	0x04f0
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_OneOnOneGerm00	0x04ef
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_SquadEncounterGerm00	0x04ed
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_StalkingPreyGerm00	0x04ec
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_TurkeyShootAL00	0x04eb
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_GermanTanks	0x0f6b
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_GermanTrucks	0x0bfb
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_OneOnOneBrit00	0x04ea
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_OneOnOneBrit01	0x04e9
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_SquadEncounterBrit00	0x04e8
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_StalkingPreyBrit00	0x04e7
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_EnemyScoutLostWp01	0x01b5
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_LoneEnemyWarnsAf	0x04a9
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_FCTroopsCambraiBoursies	0x0271
//DeadCode RDH 19Feb98 //DeadCode RDH 23Oct97 #define	T_UID_CRCSNORTHPATROL3WP00_Item00	0x0270

		
#define	IDS_BLUESTRENGTH				6000
#define	IDS_BLUEFIGHTERS				6001
#define	IDS_BLUEBOMBERS					6002
#define	IDS_REDSTRENGTH					6003
#define	IDS_REDFIGHTERS					6004
#define	IDS_REDBOMBERS					6005
#define	IDS_GREENSTRENGTH				6006
#define	IDS_AMBERSTRENGTH				6007
#define	IDS_PLYRFORMSIZE				6008
#define	IDS_RNDBLUESCOUTS				6009
#define	IDS_CONVOYCOUNT					6010
#define	IDS_PLYRWINGSIZE				6011
#define	IDS_ENEMYWINGSIZE00				6012
#define	IDS_ENEMYSCOUTTYPE00			6013
#define	IDS_ENEMYCHARGETYPE00			6014
#define	IDS_ENEMYSCOUTTYPE01			6015
#define	IDS_ENEMYCHARGETYPE01			6016
#define	IDS_CAMPAIGNENEMYSCOUTTYPE00		6017
#define	IDS_CAMPAIGNENEMYCHARGETYPE00		6018
#define	IDS_CAMPAIGNENEMYSCOUTTYPE01		6019
#define	IDS_CAMPAIGNENEMYCHARGETYPE01		6020
#define	IDS_FRIENDLYSCOUTTYPE00				6021
#define	IDS_FRIENDLYCHARGETYPE00			6022
#define	IDS_CAMPAIGNFRIENDLYSCOUTTYPE00		6023
#define	IDS_CAMPAIGNFRIENDLYCHARGETYPE00	6024
#define	IDS_H2H_PT1							6025
#define	IDS_H2H_PT2							6026
#define	IDS_H2H_PT3							6027
#define	IDS_H2H_PT4							6028
#define	IDS_H2H_PT5							6029
#define	IDS_H2H_PT6							6030
#define	IDS_H2H_PT7							6031
#define	IDS_H2H_PT8							6032
#define	IDS_NAT_ENEMY					6033
#define	IDS_NAT_FRIEND					6034
#define	IDS_FORMSIZE00					6035
#define	IDS_FORMSIZE01					6036
#define	IDS_FORMSIZE02					6037
#define	IDS_FORMSIZE03					6038
#define	IDS_ANGLESTEPSIZE				6039
#define	IDS_HEIGHTSTEPSIZE				6040
#define	IDS_RANGESTEPSIZE				6041
#define	IDS_ENCOUNTERSIZE				6042
#define	IDS_PARENTRAND					6043
#define	IDS_HEIGHTSIZE					6044
#define	IDS_CLOUDBASE					6045
#define	IDS_CAM_CAMITEM					6046
#define	IDS_CAM_TRGTITEM				6047
#define	IDS_UIDDEATHITEM				6048
#define	IDS_ENEMYSCOUTHOMEBASE			6049
#define	IDS_ENEMYCHARGEHOMEBASE			6050
#define	IDS_FRIENDLYCHARGEHOMEBASE		6051
#define	IDS_FRIENDLYSCOUTHOMEBASE		6052
#define	IDS_ENEMYOBJECTIVE				6053
#define	IDS_FRIENDLYOBJECTIVE			6054
#define	IDS_MAINOBJECTIVE				6055
#define	IDS_SUBOBJECTIVE				6056
#define	IDS_WP1							6057
#define	IDS_WP2							6058
#define	IDS_WP3							6059
#define	IDS_ENEMYHOMEBASE				6060
#define	IDS_FRIENDHOMEBASE				6061
#define	IDS_CPP							6062
#define	IDS_CWP							6063
#define	IDS_ENEMYSCOUTMORALE				6064
#define	IDS_FRIENDLYSCOUTMORALE				6065
#define	IDS_FRIENDLYCHARGEMORALE			6066
#define	IDS_ENEMYCHARGEMORALE				6067
#define	IDS_ENEMYSCOUTCHARACTER				6068
#define	IDS_ENEMYSCOUTTACTICIAN				6069
#define	IDS_ENEMYSCOUTMRAVERAGE				6070
#define	IDS_ENEMYSCOUTCAVALIER				6071
#define	IDS_FRIENDLYSCOUTCHARACTER			6072
#define	IDS_FRIENDLYSCOUTTACTICIAN			6073
#define	IDS_FRIENDLYSCOUTMRAVERAGE			6074
#define	IDS_FRIENDLYSCOUTCAVALIER			6075
#define	IDS_FRIENDLYCHARGECHARACTER			6076
#define	IDS_ENEMYCHARGECHARACTER			6077
#define	IDS_ENEMYSCOUTSKILLMIN				6078
#define	IDS_ENEMYCHARGESKILLMIN				6079
#define	IDS_FRIENDLYSCOUTSKILLMIN			6080
#define	IDS_FRIENDLYCHARGESKILLMIN			6081
#define	IDS_ENEMYSCOUTSKILLMAX				6082
#define	IDS_ENEMYCHARGESKILLMAX				6083
#define	IDS_FRIENDLYSCOUTSKILLMAX			6084
#define	IDS_FRIENDLYCHARGESKILLMAX			6085
#define	IDS_GLOBALSKILLMIN					6086
#define	IDS_GLOBALSKILLMAX					6087
#define	IDS_ENEMYSCOUTSQUAD					6088
#define	IDS_FRIENDLYSCOUTSQUAD				6089
#define	IDS_ENEMYCHARGESQUAD				6090
#define	IDS_FRIENDLYCHARGESQUAD				6091
#define	IDS_OKTOQUIT3DNOW				6092
#define	IDS_QUIT3DNOW					6093
#define	IDS_AUTOBULLETCOUNT				6094
#define	IDS_DEATHTYPE					6095
#define	IDS_CAM_VIEWTARG				6096
#define	IDS_CAM_VIEWMODE				6097
#define	IDS_CAM_CUTTYPE					6098
#define	IDS_CAM_PANRATE					6099
#define	IDS_CAM_ZOOM					4100
#define	IDS_CAM_ROLLRATE				4101
#define	IDS_CAM_ROTATERATE				4102
#define	IDS_CAM_PITCHRATE				4103
#define	IDS_SAMPLE_PLAY					4104
#define	IDS_SAMPLE_VOLUME				4105
#define	IDS_SAMPLE_PAN					4106
#define	IDS_MAINPOSX					4107
#define	IDS_MAINPOSY					4108
#define	IDS_MAINPOSZ					4109
#define	IDS_SUBPOSX						4110
#define	IDS_SUBPOSY						4111
#define	IDS_SUBPOSZ						4112
#define	IDS_CAM_HEADING					4113
#define	IDS_CAM_PITCH					4114
#define	IDS_PS_1					4115
#define	IDS_PS_2					4116
#define	IDS_PS_3					4117
#define	IDS_PS_4					4118
#define	IDS_PS_5					4119
#define	IDS_PS_6					4120
#define	IDS_PS_7					4121
#define	IDS_PS_8					4122
#define	IDS_REQUIREDNATIONALITY		4123
#define	IDS_DESPITCH				4124
#define	IDS_DESHDG					4125
#define	IDS_RANDANGLE				4126
#define	IDS_MAINACTION				4127
#define	IDS_SubAction				4128
							  




#define	IDS_HELP_BLUESTRENGTH				4200
#define	IDS_HELP_BLUEFIGHTERS				4201
#define	IDS_HELP_BLUEBOMBERS				4202
#define	IDS_HELP_REDSTRENGTH				4203
#define	IDS_HELP_REDFIGHTERS				4204
#define	IDS_HELP_REDBOMBERS					4205
#define	IDS_HELP_GREENSTRENGTH				4206
#define	IDS_HELP_AMBERSTRENGTH				4207
#define	IDS_HELP_PLYRFORMSIZE				4208
#define	IDS_HELP_RNDBLUESCOUTS				4209
#define	IDS_HELP_CONVOYCOUNT				4210
#define	IDS_HELP_PLYRWINGSIZE				4211
#define	IDS_HELP_ENEMYWINGSIZE00			4212
#define	IDS_HELP_ENEMYSCOUTTYPE00			4213
#define	IDS_HELP_ENEMYCHARGETYPE00			4214
#define	IDS_HELP_ENEMYSCOUTTYPE01			4215
#define	IDS_HELP_ENEMYCHARGETYPE01			4216
#define	IDS_HELP_CAMPAIGNENEMYSCOUTTYPE00			4217
#define	IDS_HELP_CAMPAIGNENEMYCHARGETYPE00			4218
#define	IDS_HELP_CAMPAIGNENEMYSCOUTTYPE01			4219
#define	IDS_HELP_CAMPAIGNENEMYCHARGETYPE01			4220
#define	IDS_HELP_FRIENDLYSCOUTTYPE00				4221
#define	IDS_HELP_FRIENDLYCHARGETYPE00				4222
#define	IDS_HELP_CAMPAIGNFRIENDLYSCOUTTYPE00		4223
#define	IDS_HELP_CAMPAIGNFRIENDLYCHARGETYPE00		4224
#define	IDS_HELP_H2H_PT1					4225
#define	IDS_HELP_H2H_PT2					4226
#define	IDS_HELP_H2H_PT3					4227
#define	IDS_HELP_H2H_PT4					4228
#define	IDS_HELP_H2H_PT5					4229
#define	IDS_HELP_H2H_PT6					4230
#define	IDS_HELP_H2H_PT7					4231
#define	IDS_HELP_H2H_PT8					4232
#define	IDS_HELP_NAT_ENEMY					4233
#define	IDS_HELP_NAT_FRIEND					4234
#define	IDS_HELP_FORMSIZE00					4235
#define	IDS_HELP_FORMSIZE01					4236
#define	IDS_HELP_FORMSIZE02					4237
#define	IDS_HELP_FORMSIZE03					4238
#define	IDS_HELP_ANGLESTEPSIZE				4239
#define	IDS_HELP_HEIGHTSTEPSIZE				4240
#define	IDS_HELP_RANGESTEPSIZE				4241
#define	IDS_HELP_ENCOUNTERSIZE				4242
#define	IDS_HELP_PARENTRAND					4243
#define	IDS_HELP_HEIGHTSIZE					4244
#define	IDS_HELP_CLOUDBASE					4245
#define	IDS_HELP_CAM_CAMITEM				4246
#define	IDS_HELP_CAM_TRGTITEM				4247
#define	IDS_HELP_UIDDEATHITEM				4248
#define	IDS_HELP_ENEMYSCOUTHOMEBASE			4249
#define	IDS_HELP_ENEMYCHARGEHOMEBASE		4250
#define	IDS_HELP_FRIENDLYCHARGEHOMEBASE		4251
#define	IDS_HELP_FRIENDLYSCOUTHOMEBASE		4252
#define	IDS_HELP_ENEMYOBJECTIVE				4253
#define	IDS_HELP_FRIENDLYOBJECTIVE			4254
#define	IDS_HELP_MAINOBJECTIVE				4255
#define	IDS_HELP_SUBOBJECTIVE				4256
#define	IDS_HELP_WP1						4257
#define	IDS_HELP_WP2						4258
#define	IDS_HELP_WP3						4259
#define	IDS_HELP_ENEMYHOMEBASE				4260
#define	IDS_HELP_FRIENDHOMEBASE				4261
#define	IDS_HELP_CPP						4262
#define	IDS_HELP_CWP						4263
#define	IDS_HELP_ENEMYSCOUTMORALE			4264
#define	IDS_HELP_FRIENDLYSCOUTMORALE		4265
#define	IDS_HELP_FRIENDLYCHARGEMORALE		4266
#define	IDS_HELP_ENEMYCHARGEMORALE			4267
#define	IDS_HELP_ENEMYSCOUTCHARACTER			4268
#define	IDS_HELP_ENEMYSCOUTTACTICIAN			4269
#define	IDS_HELP_ENEMYSCOUTMRAVERAGE			4270
#define	IDS_HELP_ENEMYSCOUTCAVALIER				4271
#define	IDS_HELP_FRIENDLYSCOUTCHARACTER			4272
#define	IDS_HELP_FRIENDLYSCOUTTACTICIAN			4273
#define	IDS_HELP_FRIENDLYSCOUTMRAVERAGE			4274
#define	IDS_HELP_FRIENDLYSCOUTCAVALIER			4275
#define	IDS_HELP_FRIENDLYCHARGECHARACTER		4276
#define	IDS_HELP_ENEMYCHARGECHARACTER			4277
#define	IDS_HELP_ENEMYSCOUTSKILLMIN				4278
#define	IDS_HELP_ENEMYCHARGESKILLMIN			4279
#define	IDS_HELP_FRIENDLYSCOUTSKILLMIN			4280
#define	IDS_HELP_FRIENDLYCHARGESKILLMIN			4281
#define	IDS_HELP_ENEMYSCOUTSKILLMAX				4282
#define	IDS_HELP_ENEMYCHARGESKILLMAX			4283
#define	IDS_HELP_FRIENDLYSCOUTSKILLMAX			4284
#define	IDS_HELP_FRIENDLYCHARGESKILLMAX			4285
#define	IDS_HELP_GLOBALSKILLMIN					4286
#define	IDS_HELP_GLOBALSKILLMAX					4287
#define	IDS_HELP_ENEMYSCOUTSQUAD				4288
#define	IDS_HELP_FRIENDLYSCOUTSQUAD				4289
#define	IDS_HELP_ENEMYCHARGESQUAD				4290
#define	IDS_HELP_FRIENDLYCHARGESQUAD			4291
#define	IDS_HELP_OKTOQUIT3DNOW					4292
#define	IDS_HELP_QUIT3DNOW						4293
#define	IDS_HELP_AUTOBULLETCOUNT				4294
#define	IDS_HELP_DEATHTYPE						4295
#define	IDS_HELP_CAM_VIEWTARG					4296
#define	IDS_HELP_CAM_VIEWMODE					4297
#define	IDS_HELP_CAM_CUTTYPE					4298
#define	IDS_HELP_CAM_PANRATE					4299
#define	IDS_HELP_CAM_ZOOM					4300
#define	IDS_HELP_CAM_ROLLRATE				4301
#define	IDS_HELP_CAM_ROTATERATE				4302
#define	IDS_HELP_CAM_PITCHRATE				4303
#define	IDS_HELP_SAMPLE_PLAY				4304
#define	IDS_HELP_SAMPLE_VOLUME				4305
#define	IDS_HELP_SAMPLE_PAN					4306
#define	IDS_HELP_MAINPOSX					4307
#define	IDS_HELP_MAINPOSY					4308
#define	IDS_HELP_MAINPOSZ					4309
#define	IDS_HELP_SUBPOSX					4310
#define	IDS_HELP_SUBPOSY					4311
#define	IDS_HELP_SUBPOSZ					4312
#define	IDS_HELP_CAM_HEADING				4313
#define	IDS_HELP_CAM_PITCH					4314
#define	IDS_HELP_PS_1						4315
#define	IDS_HELP_PS_2						4316
#define	IDS_HELP_PS_3						4317
#define	IDS_HELP_PS_4						4318
#define	IDS_HELP_PS_5						4319
#define	IDS_HELP_PS_6						4320
#define	IDS_HELP_PS_7						4321
#define	IDS_HELP_PS_8						4322
#define	IDS_HELP_REQUIREDNATIONALITY		4323
#define	IDS_HELP_DESPITCH					4324
#define	IDS_HELP_DESHDG						4325
#define	IDS_HELP_RANDANGLE					4326
#define	IDS_HELP_MAINACTION					4327
#define	IDS_HELP_SubAction					4328

#define	IDS_TACTICIAN	4400
#define	IDS_MRAVERAGE	4401
#define	IDS_CAVALIER	4402

#define	IDS_PLANE_TYPE_CAMEL	 	4410
#define	IDS_PLANE_TYPE_SE5a			4411
#define	IDS_PLANE_TYPE_FOKKER_DR1	4412
#define	IDS_PLANE_TYPE_ALBATROS_D3	4413
#define	IDS_PLANE_TYPE_NIEUPORT28	4414
#define	IDS_PLANE_TYPE_SPAd			4415
#define	IDS_PLANE_TYPE_FRENCHSPAD 	4416
#define	IDS_PLANE_TYPE_FOKKER_D7	4417
#define	IDS_PLANE_TYPE_NIEUPORT17	4418
#define	IDS_PLANE_TYPE_STRUTTEr		4419
#define	IDS_PLANE_TYPE_BRISTOL_F2a	4420
#define	IDS_PLANE_TYPE_PUp			4421
#define	IDS_PLANE_TYPE_FE2b			4422
#define	IDS_PLANE_TYPE_BE2c			4423
#define	IDS_PLANE_TYPE_RE8			4424
#define	IDS_PLANE_TYPE_DH9			4425
#define	IDS_PLANE_TYPE_PFALz		4426
#define	IDS_PLANE_TYPE_HALBERSTADt	4427
#define	IDS_PLANE_TYPE_ZEPP			4428
#define	IDS_PLANE_TYPE_AVIATIK_c	4429
#define	IDS_PLANE_TYPE_RUMBLER_c	4430
#define	IDS_PLANE_TYPE_SE5			4431
#define	IDS_ATRUCK					4432
#define	IDS_ATANK					4433

#define IDS_TEXT_NOVICE				4440
#define IDS_TEXT_POOR				4441
#define IDS_TEXT_REGULAR			4442
#define IDS_TEXT_VETERAN			4443
#define IDS_TEXT_ACE				4444
#define IDS_TEXT_HERO				4445
#define IDS_TEXT_ROCKBOTTOM			4446
#define IDS_TEXT_VERYPOOR			4447
#define IDS_TEXT_POORMORALE			4448
#define IDS_TEXT_AVERAGE			4449
#define IDS_TEXT_GOODMORALE			4450
#define IDS_TEXT_VERYGOOD			4451
#define IDS_TEXT_EXCELLENT			4452

#define IDS_TEXTENCOUNTER0			4460
#define IDS_TEXTENCOUNTER1          4461
#define IDS_TEXTENCOUNTER2          4462
#define IDS_TEXTENCOUNTER3          4463
#define IDS_TEXTENCOUNTER4          4464
#define IDS_TEXTENCOUNTER5          4465
#define IDS_TEXTENCOUNTER6          4466
#define IDS_TEXTENCOUNTER7          4467
#define IDS_TEXTENCOUNTER8          4468



#define	IDS_TEXT_FLYWPACNOACTIONNO		4500
#define	IDS_TEXT_FLYWPATAKEOFFNO		4501
#define	IDS_TEXT_FLYWPACIRCLENO			4502
#define	IDS_TEXT_FLYWPALANDINGNO		4503
#define	IDS_TEXT_FLYWPSTARTLOOPNO		4504
#define	IDS_TEXT_FLYWPSTOPLOOPCHKNO		4505
#define	IDS_TEXT_FLYWPRECCYNO			4506
#define	IDS_TEXT_FLYWPARTSPOTNO			4507
#define	IDS_TEXT_FLYWPENGAGETARGETNO	4508
#define	IDS_TEXT_FLYWPATTACKCONVOYNO	4509
#define	IDS_TEXT_FLYWPBALLOONBUSTNO		4510
#define	IDS_TEXT_FLYWPBOMBNO			4511
#define	IDS_TEXT_FLYWPDIVEBOMBSTRAFFENO	4512
#define	IDS_TEXT_FLYWPSTRAFFENO			4513
#define	IDS_TEXT_FLYWPBREAKLOOP			4514
#define	IDS_TEXT_FLYWPWAITUNTILDEADNO	4515
#define	IDS_TEXT_FLYWPDMBTRKNOACTNO		4516
#define	IDS_TEXT_FLYWPDMBTRKSTOPNO		4517
#define	IDS_TEXT_FLYWPTRUCKBRIDGE		4518
#define	IDS_TEXT_FLYWPTRUCKESCORT		4519
#define	IDS_TEXT_FLYWPSTOPNO			4520
#define	IDS_TEXT_WPFIREGUN				4521
#define	IDS_TEXT_FLYWPTELEPORTNEXT		4522

#define	    IDS_TEXT_ENCOUNTERRANGE2000			4530
#define	    IDS_TEXT_ENCOUNTERRANGE3000			4531
#define	    IDS_TEXT_ENCOUNTERRANGESTANDARD 	4532
#define	    IDS_TEXT_ENCOUNTERRANGE5000			4533
#define	    IDS_TEXT_ENCOUNTERRANGE6000			4534
#define	    IDS_TEXT_ENCOUNTERRANGE7000			4535

#define	    IDS_NEUTRAL				4540
#define	    IDS_CENTRALPOWERS       4541
#define	    IDS_ALLIES              4542

#define	    IDS_REGIONSOMME			4550				   					   
#define	    IDS_REGIONVERDUN		4551

#define		IDS_FIL_MainWorld			4560
#define		IDS_FIL_SpringWorld			4561
#define		IDS_FIL_SpringWorld1		4562
#define		IDS_FIL_SpringWorld1A		4563
#define		IDS_FIL_SpringWorld2		4564
#define		IDS_FIL_TankWorld			4565
#define		IDS_FIL_CircusWorld			4566
#define		IDS_FIL_HatWorld			4567
#define		IDS_FIL_HR12Sep				4568
#define		IDS_FIL_HatWorld2			4569
#define		IDS_FIL_HatWorld3			4570
#define		IDS_FIL_HatWorld5			4571

#define		T_SELECTHOMEBASE			4580
#define		T_AIRFIELD					4581
								   



#define		T_PilotedAcBANDNum					4600
#define		T_WayPointBANDNum					4601
#define		T_RedGroundMobileBANDNum			4602
#define		T_BlueGroundMobileBANDNum			4603
#define		T_MissileBANDNum					4604
#define		T_RedAcBANDNum						4605
#define		T_BlueAcBANDNum						4606
#define		T_RedCivilianBANDNum				4607
#define		T_BlueCivilianBANDNum				4608
#define		T_GreenCivilianBANDNum				4609
#define		T_RedVetoedBANDNum					4610
#define		T_BlueVetoedBANDNum					4611
#define		T_LandscapeBANDNum					4612
#define		T_RedMilitaryBANDNum				4613
#define		T_BlueMilitaryBANDNum				4614
#define		T_RedAirfieldBANDNum				4615
#define		T_BlueAirfieldBANDNum				4616
#define		T_RedPortBANDNum					4617
#define		T_BLuePortBANDNum					4618
#define		T_RedCCCBANDNum						4619
#define		T_BlueCCCBANDNum					4620
#define		T_RedGICBANDNum						4621
#define		T_BlueGICBANDNum					4622
#define		T_RedAAASiteBANDNum					4623
#define		T_BlueAAASiteBANDNum				4624
#define		T_RedSAMBANDNum						4625
#define		T_BlueSAMBANDNum					4626



#define		TEXT_JANUARY						4640
#define		TEXT_FEBRUARY						4641
#define		TEXT_MARCH							4642
#define		TEXT_APRIL							4643
#define		TEXT_MAYY							4644
#define		TEXT_JUNE							4645
#define		TEXT_JULY							4646
#define		TEXT_AUGUST							4647
#define		TEXT_SEPTEMBER						4648
#define		TEXT_OCTOBER						4649
#define		TEXT_NOVEMBER						4650
#define		TEXT_DECEMBER						4651

#define		IDS_SQUADRONINFO					4655


#define		IDS_TEXT_SECLIEUTENANT					4660
#define		IDS_TEXT_SECLIEUTENANTSNR				4661
#define		IDS_TEXT_LIEUTENANT		   	            4662
#define		IDS_TEXT_CAPTAIN			            4663
#define		IDS_TEXT_MAJOR				            4664

#define		IDS_TEXT_FAHNRICH			            4665
#define		IDS_TEXT_FAHNRICHSNR		            4666
#define		IDS_TEXT_LEUTNANT			            4667
#define		IDS_TEXT_OBERLEUTNANT		            4668
#define		IDS_TEXT_RITTMEISTER		            4669

#define		TEXT_MISSIONEDITTING   	            4670
#define		TEXT_CAMPAIGNEDITTING	            4671
#define		TEXT_MISSION		   	            4672
#define		TEXT_NEWCAMPAIGN   	   	            4673
#define		TEXT_SAVECAMPAIGNEDIT  	            4674
#define		TEXT_SAVEMISSIONEDIT  	            4675

#define		IDS_TEXT_STACKED						4680
#define		IDS_TEXT_STACKEDBOX         			4681
#define		IDS_TEXT_DIAMOND						4682
#define		IDS_TEXT_FLATBOX            			4683
#define		IDS_TEXT_FLATV							4684
#define		IDS_TEXT_TWOV							4685
#define		IDS_TEXT_FILLEDV            			4686
#define		IDS_TEXT_SHEPHERD           			4687
#define		IDS_TEXT_LOOSE_FORM						4688
//h2h2 formations
#define		IDS_TEXT_RANDOM_FORM					4689
#define		IDS_TEXT_IMPLODE_FORM					4690
#define		IDS_TEXT_EXPLODE_FORM					4691
#define		IDS_TEXT_TAKEOFF_FORM					4692
#define		IDS_TEXT_SINGLEFILE_FORM				4693

#define			IDS_TEXT_NORTH                      4700
#define			IDS_TEXT_NORTHEAST                  4701
#define			IDS_TEXT_EAST                       4702
#define			IDS_TEXT_SOUTHEAST                  4703
#define			IDS_TEXT_SOUTH                      4704
#define			IDS_TEXT_SOUTHWEST                  4705
#define			IDS_TEXT_WEST                       4706
#define			IDS_TEXT_NORTHWEST                  4707

#define			IDS_TEXT_LOWCLOUD                   4710
#define			IDS_TEXT_CLOUD10000                 4711
#define			IDS_TEXT_BADWEATHER                 4712
#define			IDS_TEXT_LOWCLOUDM                  4713
#define			IDS_TEXT_CLOUD10000M                4714
#define			IDS_TEXT_BADWEATHERM                4715

#define			TEXT_UNITSMETRIC  					4720
#define			TEXT_UNITSIMPERIAL                  4721
#define			TEXT_UNITSMIXED		                4722
#define			TEXT_VEHICLEMOBILE					4723
#define			TEXT_VEHICLESTATIC                  4724

#define			TEXT_NEWSINGLEMISSION  				4730
#define			TEXT_NEWCAMPAIGNMISSION             4731
#define			TEXT_OPENSINGLEMISSION  			4732
#define			TEXT_OPENCAMPAIGNMISSION            4733
#define			TEXT_SAVESINGLEMISSION  			4734
#define			TEXT_SAVECAMPAIGNMISSION            4735
#define			TEXT_SAVEASSINGLEMISSION  			4736
#define			TEXT_SAVEASCAMPAIGNMISSION          4737

#define			TEXT_MMDDYY							4740
#define			TEXT_DDMMYY                         4741
#define			TEXT_FIRSTMISSION					4742
#define			TEXT_NONAME							4743


#define			TEXT_SQUADRONPILOTS					4750
#define			TEXT_ACEPILOTS						4751
#define			TEXT_RESERVEPILOTS					4752
//DeadCode RDH 19Feb98 
//DeadCode RDH 19Feb98 
//DeadCode RDH 19Feb98 #define			TEXT_FLAKBRIT						4802
//DeadCode RDH 19Feb98 //#define			TEXT_FLKBRIT2						4802
//DeadCode RDH 19Feb98 #define			TEXT_SNDBGA							4803
//DeadCode RDH 19Feb98 #define			TEXT_AAAB							4804
//DeadCode RDH 19Feb98 #define			TEXT_ONIONB							4805
//DeadCode RDH 19Feb98 //#define			TEXT_NULL							4806
//DeadCode RDH 19Feb98 #define			TEXT_FLAKGERM						4807
//DeadCode RDH 19Feb98 //#define			TEXT_FLKGERM2						4807
//DeadCode RDH 19Feb98 #define			TEXT_SNDBGG							4808
//DeadCode RDH 19Feb98 #define			TEXT_AAAG							4809
//DeadCode RDH 19Feb98 #define			TEXT_ONIONG							4810
//DeadCode RDH 19Feb98 //#define			TEXT_NULL							4811
//DeadCode RDH 19Feb98 #define			TEXT_BTHBRIT						4812
//DeadCode RDH 19Feb98 #define			TEXT_BTHUSA							4813
//DeadCode RDH 19Feb98 #define			TEXT_BTLBRIT						4814
//DeadCode RDH 19Feb98 #define			TEXT_BTLUSA							4815
//DeadCode RDH 19Feb98 #define			TEXT_AHGUN							4816
//DeadCode RDH 19Feb98 #define			TEXT_ALGUN							4817
//DeadCode RDH 19Feb98 //#define			TEXT_NULL							4818
//DeadCode RDH 19Feb98 #define			TEXT_BTHGERM						4819
//DeadCode RDH 19Feb98 #define			TEXT_BTLGERM						4820
//DeadCode RDH 19Feb98 #define			TEXT_GHGUN							4821
//DeadCode RDH 19Feb98 #define			TEXT_GLGUN							4822
//DeadCode RDH 19Feb98 //#define			TEXT_NULL							4823
//DeadCode RDH 19Feb98 #define			TEXT_STAFF							4824
//DeadCode RDH 19Feb98 #define			TEXT_TRUCK							4825
//DeadCode RDH 19Feb98 //#define			TEXT_NULL							4826
//DeadCode RDH 19Feb98 #define			TEXT_TROOPS							4827
//DeadCode RDH 19Feb98 #define			TEXT_TROOP1							4828
//DeadCode RDH 19Feb98 //#define			TEXT_NULL							4829
//DeadCode RDH 19Feb98 #define			TEXT_TRAIN3							4830
//DeadCode RDH 19Feb98 #define			TEXT_TRAIN4							4831
//DeadCode RDH 19Feb98 //#define			TEXT_NULL							4832
//DeadCode RDH 19Feb98 #define			TEXT_FARMYRD						4833
//DeadCode RDH 19Feb98 #define			TEXT_VILLAGE						4834
//DeadCode RDH 19Feb98 #define			TEXT_DEADTOWN						4835
//DeadCode RDH 19Feb98 #define			TEXT_WOOD							4836
//DeadCode RDH 19Feb98 //#define			TEXT_NULL					   4837
//DeadCode RDH 19Feb98 #define			TEXT_AMMO						    4838
//DeadCode RDH 19Feb98 #define			TEXT_BARN						    4839
//DeadCode RDH 19Feb98 #define			TEXT_BARN2						    4840
//DeadCode RDH 19Feb98 #define			TEXT_BLOCK						    4841
//DeadCode RDH 19Feb98 #define			TEXT_CART						    4842
//DeadCode RDH 19Feb98 #define			TEXT_CMTENT						    4843
//DeadCode RDH 19Feb98 #define			TEXT_COTAGE							4844
//DeadCode RDH 19Feb98 #define			TEXT_CRANE							4845
//DeadCode RDH 19Feb98 #define			TEXT_CHTAU2							4846
//DeadCode RDH 19Feb98 #define			TEXT_FARM							4847
//DeadCode RDH 19Feb98 #define			TEXT_NETT1							4848
//DeadCode RDH 19Feb98 #define			TEXT_NETT2							4849
//DeadCode RDH 19Feb98 #define			TEXT_NETT3							4850
//DeadCode RDH 19Feb98 #define			TEXT_OPPS1							4851
//DeadCode RDH 19Feb98 #define			TEXT_OPPS2							4852
//DeadCode RDH 19Feb98 #define			TEXT_PLATFM							4853
//DeadCode RDH 19Feb98 #define			TEXT_SLEPER							4854
//DeadCode RDH 19Feb98 #define			TEXT_SMLHNG							4855
//DeadCode RDH 19Feb98 #define			TEXT_SMTENT							4856
//DeadCode RDH 19Feb98 #define			TEXT_SNDBG							4857
//DeadCode RDH 19Feb98 #define			TEXT_WDHUT1							4858
//DeadCode RDH 19Feb98 #define			TEXT_WDHUT2							4859
//DeadCode RDH 19Feb98 #define			TEXT_AFHUT							4860
//DeadCode RDH 19Feb98 #define			TEXT_AFTENT							4861
//DeadCode RDH 19Feb98 #define			TEXT_TREE							4862
//DeadCode RDH 19Feb98 #define			TEXT_CHTAU4							4863
//DeadCode RDH 19Feb98 #define			TEXT_RCTENT							4864
//DeadCode RDH 19Feb98 #define			TEXT_NEW1							4865
//DeadCode RDH 19Feb98 #define			TEXT_NEW6							4866
//DeadCode RDH 19Feb98 #define			TEXT_NEW12							4867
//DeadCode RDH 19Feb98 #define			TEXT_WRECK							4868
//DeadCode RDH 19Feb98 #define			TEXT_CHTEAU							4869
//DeadCode RDH 19Feb98 #define			TEXT_CHTAU3							4870
//DeadCode RDH 19Feb98 #define			TEXT_CHTAU5							4871
//DeadCode RDH 19Feb98 #define			TEXT_FUEL							4872
//DeadCode RDH 19Feb98 #define			TEXT_DHOUS1							4873
//DeadCode RDH 19Feb98 #define			TEXT_DHOUS2							4874
//DeadCode RDH 19Feb98 #define			TEXT_DHOUS3							4875
//DeadCode RDH 19Feb98 #define			TEXT_AFHANG							4876
//DeadCode RDH 19Feb98 #define			TEXT_BPOLE							4877
//DeadCode RDH 19Feb98 #define			TEXT_GPOLE							4878
//DeadCode RDH 19Feb98 #define			TEXT_UPOLE							4879
//DeadCode RDH 19Feb98 #define			TEXT_WINDSC							4880
//DeadCode RDH 19Feb98 #define			TEXT_AMMO2							4881
//DeadCode RDH 19Feb98 #define			TEXT_AMMO3							4882
//DeadCode RDH 19Feb98 #define			TEXT_AMMO4							4883
//DeadCode RDH 19Feb98 #define			TEXT_BARRAGE						4884
//DeadCode RDH 19Feb98 
//DeadCode RDH 19Feb98 //
//DeadCode RDH 19Feb98 #define			TEXT_BTANK							4886
//DeadCode RDH 19Feb98 //
//DeadCode RDH 19Feb98 #define			TEXT_GTANK							4888
//DeadCode RDH 19Feb98 //
//DeadCode RDH 19Feb98 #define			TEXT_BBALL							4890
//DeadCode RDH 19Feb98 //
//DeadCode RDH 19Feb98 #define			TEXT_GBALL							4892
//DeadCode RDH 19Feb98 //
//DeadCode RDH 19Feb98 #define			TEXT_STGGERM                        4894
//DeadCode RDH 19Feb98 #define			TEXT_AFHGERM                        4895
//DeadCode RDH 19Feb98 #define			TEXT_AFHBRIT                        4896
//DeadCode RDH 19Feb98 #define			TEXT_AFHUSA                         4897
//DeadCode RDH 19Feb98 #define			TEXT_AFLGERM                        4898
//DeadCode RDH 19Feb98 #define			TEXT_AFLBRIT                        4899
//DeadCode RDH 19Feb98 #define			TEXT_AFLUSA                         4900
//DeadCode RDH 19Feb98 #define			TEXT_AFBARON1                       4901
//DeadCode RDH 19Feb98 #define			TEXT_AFBARON2                       4902
//DeadCode RDH 19Feb98 #define			TEXT_STGBRIT                        4903
//DeadCode RDH 19Feb98 #define			TEXT_STGUSA                         4904
//DeadCode RDH 19Feb98 //	leave blank                                                    4905

#define			TEXT_SPD								5000
#define			TEXT_ETAAT							5001
#define			TEXT_WPRANGE						5002
#define			TEXT_ALT								5003
#define			TEXT_MINVEL							5004
#define			TEXT_CRUISE							5005
#define			TEXT_MAXVEL                   5006
#define			TEXT_CUSTOM                   5007


#define			TEXT_SQUADTITLE					5015
#define			TEXT_ACESTITLE					5016
#define			TEXT_RESTITLE					5017
#define			TEXT_NOTENOUGHEDITS				5018
#define			TEXT_NOEDITS					5019

#define			TEXT_NEWCAMPTITLE				5020
#define			TEXT_NEWMISSTITLE				5021
#define			TEXT_VIEWMISSTITLE				5022
#define			TEXT_SAVEMISSTITLE				5023
#define			TEXT_CANTSAVEPARTIAL			5024

#define			TEXT_SELECTDIR					5025
#define			TEXT_NEWGRP						5026
#define			TEXT_SUREOPENDIR                5027
#define			TEXT_OPENGRP                    5028
#define			TEXT_SURENEWDIR                 5029
#define			TEXT_NEWCAMP                    5030
#define			TEXT_OPENCAMP                   5031
#define			TEXT_SELECTFILE                 5032
#define			TEXT_OPENMISS                   5033
#define			TEXT_SURENEWMISS                5034
#define			TEXT_NEWMISS                    5035
#define			TEXT_SUREOPENMISS               5036
#define			TEXT_RENAMEMISS                 5037
#define			TEXT_LOADFROMMISS               5038
#define			TEXT_SAVEFILE                   5039
#define			TEXT_LOADFROMMISSTITLE          5040
#define			TEXT_SAVEMISSNAME               5041
#define			TEXT_SAVEALERTTITLE             5042
#define			TEXT_SAVEALERT                  5043
#define			TEXT_SAVEALERTNONAME            5044


#define			TEXT_0 		5050	
#define			TEXT_1		5051 
#define			TEXT_2 		5052
#define			TEXT_3 		5053
#define			TEXT_4 		5054
#define			TEXT_5		5055 
#define			TEXT_6 		5056
#define			TEXT_7 		5057
#define			TEXT_8		5058 

#define			TEXT_CHOOSESCENARIOS		5060

#define		   TEXT_FRIENDLIES			5061
#define		   TEXT_ENEMIES 				5062
#define		   TEXT_AVAILAIRCRAFTEXCEEDED 5063
#define		   TEXT_VARNOTSETTITLE		5064
#define		   TEXT_VARNOTSETTEXT      5065
#define		   TEXT_WAYPOINTSEXCEEDEDTEXT	5066
#define		   TEXT_WAYPOINTSEXCEEDEDTITLE	5067 

#define		   TEXT_MOBILESEXCEEDEDTITLE	5068
#define		   TEXT_MOBILESEXCEEDEDTEXT	5069

#define			TEXT_LOADFROMPILOT               5070
#define			TEXT_LOADFROMPILOTTITLE          5071

#define        TEXT_FILE_0LEN				5072
#define        TEXT_FILE_DIGIT	            5073
#define        TEXT_FILE_ILLEGAL			5074			
#define			TEXT_CHANGEOTHERSNOUNDO		5075
#define			TEXT_CHANGEOTHERS			5076

//text below here was added on or after 12 Sept 97

#define		TEXT_EVENT				5100
//dummy entries
#define			TEXT_FLKBRIT2						5101
#define			TEXT_FLKGERM2						5102

#define			TEXT_RUSURE					5103
#define			TEXT_RELATIVEALT					5104

#define			TEXT_STARTWP					5105
#define			TEXT_FINALWP					5106
#define			TEXT_SCALE					5107

#define			TEXT_WAYPOINTINLIST			5108
#define			TEXT_EVENTINLIST			5109
#define			TEXT_SPD2	  				5110
#define			TEXT_SCHEME					5111
#define			TEXT_DIFFRND				5112
#define			TEXT_SAMERND				5113
#define			TEXT_UNDEFINED				5114

#define			TEXT_TankShape				5115
#define         TEXT_TroopShape				5116
#define         TEXT_GunShape               5117
#define         TEXT_DefendBarageShape      5118
#define         TEXT_Truck1Shape            5119
#define         TEXT_Truck2Shape            5120
#define         TEXT_TentsShape             5121
#define         TEXT_ParkedACShape          5122

//block above at 6000
